#!/bin/bash
# script to preserve the intermediates
start=`date +%s`
/root/olpc-os-builder/osbuilder.py /root/mksdcard/fc18-enhanced-xo1.ini --no-clean-intermediates myplug 2>&1  | tee -a build/intermediates/build.log
end=`date +%s`

let deltatime=end-start
let hours=deltatime/3600
let minutes=(deltatime/60)%60
let seconds=deltatime%60
printf "Time spent: %d:%02d:%02d\n" $hours $minutes $seconds
