#!/bin/bash
# script to preserve the intermediates
/root/olpc-os-builder/osbuilder.py examples/client_xo1_restricted.ini restricted_fc20.ini --no-clean-intermediates 2>&1  | tee -a build/intermediates/build.log
